defaults: &defaults
  docker:
    - image: circleci/node:10.16

aliases:
  - &restore_npm
    restore_cache:
      keys:
        - cra-npm-{{ checksum "yarn.lock" }}
  - &save_npm
    save_cache:
      paths:
        - ./node_modules
        - ./packages/*/node_modules
      key: genesis-npm-{{ checksum "yarn.lock" }}
  - &yarn_install
    run: yarn install --frozen-lockfile

version: 2.1
  publish-package: 
    <<: *defaults
    steps:
      - checkout
      - *restore_npm
      - *yarn_install
      - *save_npm
      - run: yarn publish-package

workflows:
  version: 2.1
  publish_to_private_registry:
    jobs:
      - publish-package:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(\.[a-zA-Z]+)?/
